package api

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"net/url"

	"github.com/dhcgn/GitLabFileDownloader/internal"
)

func GetFilesFromFolder(settings internal.Settings) ([]string, error) {
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}

	apiUrl := fmt.Sprintf("%vprojects/%v/repository/tree/?ref=%v&path=%v", settings.ApiUrl, settings.ProjectNumber, settings.Branch, settings.RepoFolderPath)

	req, err := http.NewRequest("GET", apiUrl, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Private-Token", settings.PrivateToken)
	req.Header.Add("User-Agent", settings.UserAgent)

	client := &http.Client{Transport: tr}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	err = resp.Body.Close()
	if err != nil {
		return nil, err
	}

	var responseStruct AutoGenerated
	json.Unmarshal(body, &responseStruct)

	var files []string
	for _, file := range responseStruct {
		files = append(files, file.Path)
	}

	return files, nil
}

type AutoGenerated []struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	Path string `json:"path"`
	Mode string `json:"mode"`
}

func GetFile(settings internal.Settings) (error, int, string, GitLapFile) {
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}

	apiUrl := fmt.Sprintf("%vprojects/%v/repository/files/%v?ref=%v", settings.ApiUrl, settings.ProjectNumber, url.QueryEscape(settings.RepoFilePath), settings.Branch)

	req, err := http.NewRequest("GET", apiUrl, nil)
	if err != nil {
		return err, 0, "", GitLapFile{}
	}
	req.Header.Add("Private-Token", settings.PrivateToken)
	req.Header.Add("User-Agent", settings.UserAgent)

	client := &http.Client{Transport: tr}
	resp, err := client.Do(req)
	if err != nil {
		return err, 0, "", GitLapFile{}
	}
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return err, 0, "", GitLapFile{}
	}
	err = resp.Body.Close()
	if err != nil {
		return err, 0, "", GitLapFile{}
	}

	file, err := createGitLapFile(body)
	return err, resp.StatusCode, resp.Status, file

}

func createGitLapFile(data []byte) (GitLapFile, error) {
	var gitLapFile GitLapFile
	err := json.Unmarshal(data, &gitLapFile)
	return gitLapFile, err
}

type GitLapFile struct {
	FileName      string `json:"file_name"`
	ContentSha256 string `json:"content_sha256"`
	Content       string
}
